import { lazy, LazyExoticComponent, ComponentType } from "react";
import { FileCode, Type, Globe, FileJson } from "lucide-react";

export type ToolCategory = "Converter" | "Web" | "Development";

export const categories: ToolCategory[] = ["Converter", "Web", "Development"];

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: React.ElementType;
  component: LazyExoticComponent<ComponentType<unknown>>;
}

export const tools: Tool[] = [
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between different naming conventions.",
    category: "Converter",
    icon: Type,
    component: lazy(() => import("../tools/converter/CaseConverter")),
  },
  {
    id: "nato-alphabet",
    name: "Text to NATO Alphabet",
    description: "Convert text to NATO phonetic alphabet.",
    category: "Converter",
    icon: Type,
    component: lazy(() => import("../tools/converter/NatoAlphabetConverter")),
  },
  {
    id: "ascii-binary",
    name: "Text to ASCII Binary",
    description: "Convert text to ASCII binary representation and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/AsciiBinaryConverter")),
  },
  {
    id: "text-to-unicode",
    name: "Text to Unicode",
    description: "Convert text to Unicode escape sequences and vice versa.",
    category: "Converter",
    icon: Type,
    component: lazy(() => import("../tools/converter/TextToUnicode")),
  },
  {
    id: "list-converter",
    name: "List Converter",
    description: "Convert newline-separated lists to other formats.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/ListConverter")),
  },
  {
    id: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert integers to Roman numerals and vice versa.",
    category: "Converter",
    icon: Type,
    component: lazy(() => import("../tools/converter/RomanNumeralConverter")),
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown text to HTML preview.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/MarkdownToHtml")),
  },
  {
    id: "yaml-json",
    name: "YAML <> JSON Converter",
    description: "Convert YAML to JSON and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/YamlJsonConverter")),
  },
  {
    id: "yaml-toml",
    name: "YAML <> TOML Converter",
    description: "Convert YAML to TOML and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/YamlTomlConverter")),
  },
  {
    id: "json-toml",
    name: "JSON <> TOML Converter",
    description: "Convert JSON to TOML and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/JsonTomlConverter")),
  },
  {
    id: "xml-json",
    name: "XML <> JSON Converter",
    description: "Convert XML to JSON and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/XmlJsonConverter")),
  },
  {
    id: "date-time-converter",
    name: "Date-time Converter",
    description: "Convert dates between various formats.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/DateTimeConverter")),
  },
  {
    id: "integer-base-converter",
    name: "Integer Base Converter",
    description:
      "Convert numbers between binary, octal, decimal, and hexadecimal.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/IntegerBaseConverter")),
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, CMYK.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/ColorConverter")),
  },
  {
    id: "base64-file-converter",
    name: "Base64 File Converter",
    description: "Convert files to Base64 string and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/Base64FileConverter")),
  },
  {
    id: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Common Git commands and their usage.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/GitCheatsheet")),
  },
  {
    id: "random-port-generator",
    name: "Random Port Generator",
    description: "Generate random port numbers outside the well-known range.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/RandomPortGenerator")),
  },
  {
    id: "crontab-generator",
    name: "Crontab Generator",
    description: "Generate and explain crontab expressions.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/CrontabGenerator")),
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON array of objects to CSV format.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/JsonToCsv")),
  },
  {
    id: "sql-prettify",
    name: "SQL Prettify/Format",
    description: "Format and prettify SQL queries.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/SqlPrettify")),
  },
  {
    id: "docker-run-to-compose",
    name: "Docker Run to Compose",
    description: "Convert docker run commands to docker-compose.yml.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/DockerRunToCompose")),
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate chmod permissions in octal and symbolic formats.",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/ChmodCalculator")),
  },
  {
    id: "email-normalizer",
    name: "Email Normalizer",
    description:
      "Normalize email addresses (e.g. remove dots and tags for Gmail).",
    category: "Development",
    icon: FileCode,
    component: lazy(() => import("../tools/development/EmailNormalizer")),
  },
  {
    id: "base64-converter",
    name: "Base64 Converter",
    description: "Convert text to Base64 and vice versa.",
    category: "Converter",
    icon: FileCode,
    component: lazy(() => import("../tools/converter/Base64Converter")),
  },
  {
    id: "escape-html",
    name: "Escape HTML Entities",
    description: "Escape or unescape HTML entities.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/EscapeHtml")),
  },
  {
    id: "slugify-string",
    name: "Slugify String",
    description: "Convert string to URL-friendly slug.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/SlugifyString")),
  },
  {
    id: "basic-auth-generator",
    name: "Basic Auth Generator",
    description: "Generate HTTP Basic Authentication header.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/BasicAuthGenerator")),
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    description: "List of HTTP status codes and their descriptions.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/HttpStatusCodes")),
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description:
      "Parse URL into protocol, hostname, port, path, query params, etc.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/UrlParser")),
  },
  {
    id: "device-information",
    name: "Device Information",
    description:
      "Display current device information (screen size, pixel ratio, user agent).",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/DeviceInformation")),
  },
  {
    id: "user-agent-parser",
    name: "User-Agent Parser",
    description: "Parse User-Agent string to identify browser, OS, device.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/UserAgentParser")),
  },
  {
    id: "jwt-parser",
    name: "JWT Parser",
    description: "Decode JWT tokens (header, payload) without verification.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/JwtParser")),
  },
  {
    id: "open-graph-generator",
    name: "Open Graph Meta Generator",
    description: "Generate Open Graph meta tags for your website.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/OpenGraphGenerator")),
  },
  {
    id: "otp-generator",
    name: "OTP Code Generator",
    description: "Generate TOTP codes based on a secret key.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/OtpGenerator")),
  },
  {
    id: "mime-types",
    name: "MIME Types",
    description: "Searchable list of MIME types and extensions.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/MimeTypes")),
  },
  {
    id: "keycode-info",
    name: "Keycode Info",
    description: "Press any key to see its keycode, key, location, etc.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/KeycodeInfo")),
  },
  {
    id: "html-wysiwyg",
    name: "HTML WYSIWYG Editor",
    description: "Simple HTML WYSIWYG editor.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/HtmlWysiwyg")),
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs.",
    category: "Web",
    icon: Type,
    component: lazy(() => import("../tools/web/LoremIpsumGenerator")),
  },

  {
    id: "url-converter",
    name: "URL Encoder/Decoder",
    description: "Encode or decode URL-formatted strings.",
    category: "Web",
    icon: Globe,
    component: lazy(() => import("../tools/web/UrlConverter")),
  },
  {
    id: "json-formatter",
    name: "JSON Prettify/Minify",
    description: "Format or minify JSON data.",
    category: "Development",
    icon: FileJson,
    component: lazy(() => import("../tools/development/JsonFormatter")),
  },
];
